baseURL = 'https://thijs-creemers.github.io/boundary/'
languageCode = 'en-us'
title = 'Boundary Framework Documentation'
theme = 'hugo-book'

# Security configuration
[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']

# Enable AsciiDoc support
[markup]
  defaultMarkdownHandler = 'goldmark'
  
  [markup.asciidocExt]
    backend = 'html5'
    docType = 'article'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = true
  
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'github'
    tabWidth = 4

[params]
  # Book theme specific configuration
  BookRepo = 'https://github.com/thijs-creemers/boundary'
  BookEditPath = 'edit/main'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false
  BookToC = true
  BookMenuBundle = '/menu'
  BookSection = '*'
  BookFlatSection = false
  BookCollapseSection = false

# Menu configuration
[menu]
  [[menu.before]]
    identifier = 'github'
    name = 'GitHub'
    url = 'https://github.com/thijs-creemers/boundary'
    weight = 10

# Output formats
[outputs]
  home = ['HTML', 'RSS', 'JSON']

# Taxonomies
[taxonomies]
  tag = 'tags'
  category = 'categories'